title: Thomas Chaplin

plugins:
- jekyll-redirect-from
- jekyll-paginate

paginate: 5

paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->

sass:
    style: compressed


collections:
    posts:
        output: true
        permalink: /blog/:year_:month_:day/:title/
    portfolio_entries:
        output: true
        permalink: /portfolio/:year_:month_:day/:title/

kramdown:
 input: markdown
